# Quickstart Tutorial

## An example

The class is called **numpy.ndarray**(alias: **array**), which is different from array.array. The dimensions are called **axes**. The num of axes is called **ranks**.

In [1]:
import numpy as np

In [2]:
a=np.arange(15).reshape(3,5)

In [3]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [4]:
a.shape

(3, 5)

In [5]:
a.ndim

2

In [6]:
a.dtype.name

'int64'

In [7]:
a.itemsize

8

In [8]:
a.size

15

In [9]:
type(a)

numpy.ndarray

In [10]:
b=np.array([6,7,8])

In [11]:
b

array([6, 7, 8])

In [12]:
type(b)

numpy.ndarray

## Array Creation

In [13]:
import numpy as np

In [14]:
a=np.array([2,3,4])

In [15]:
a

array([2, 3, 4])

In [16]:
a.dtype

dtype('int64')

In [17]:
b=np.array([1.2,3.5,5.1])

In [18]:
b.dtype

dtype('float64')

In [19]:
b=np.array([(1.5,2,3),(4,5,6)])

In [20]:
b

array([[ 1.5,  2. ,  3. ],
       [ 4. ,  5. ,  6. ]])

We can explictly specify the data type at the creation time.

In [21]:
c=np.array([[1,2],[3,4]],dtype=complex)

In [22]:
c

array([[ 1.+0.j,  2.+0.j],
       [ 3.+0.j,  4.+0.j]])

Often, the elements of an array are originally unknown, but its size is known. Hence, NumPy offers several functions to create arrays with initial placeholder content. These minimize the necessity of growing arrays, an expensive operation.

* zeors
* ones
* empty: random, depending on the state of memory

By default, the dtype is float64

In [23]:
np.zeros((3,4))

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [24]:
np.ones((2,3,4),dtype=np.int16)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [25]:
np.empty((2,3))

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [26]:
np.arange(10,30,5)

array([10, 15, 20, 25])

In [27]:
np.arange(0,2,0.3)

array([ 0. ,  0.3,  0.6,  0.9,  1.2,  1.5,  1.8])

In [28]:
from numpy import pi
np.linspace(0,2,9)

array([ 0.  ,  0.25,  0.5 ,  0.75,  1.  ,  1.25,  1.5 ,  1.75,  2.  ])

In [29]:
np.linspace(0,2*pi,5)

array([ 0.        ,  1.57079633,  3.14159265,  4.71238898,  6.28318531])

## Print Arrays

In [30]:
a=np.arange(6)
print(a)

[0 1 2 3 4 5]


In [31]:
b=np.arange(12).reshape(3,4)
print(b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [32]:
c=np.arange(24).reshape(2,3,4)
print(c)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [33]:
print(np.arange(1000000))

[     0      1      2 ..., 999997 999998 999999]


In [34]:
print(np.arange(10000).reshape(100,100))

[[   0    1    2 ...,   97   98   99]
 [ 100  101  102 ...,  197  198  199]
 [ 200  201  202 ...,  297  298  299]
 ..., 
 [9700 9701 9702 ..., 9797 9798 9799]
 [9800 9801 9802 ..., 9897 9898 9899]
 [9900 9901 9902 ..., 9997 9998 9999]]


To disable this behaviour and force NumPy to print the entire array, you can change the printing options using set_printoptions.
> np.set_printoptions(threshold='nan')

## Basic Operations

In [35]:
import numpy as np

In [36]:
a=np.array([20,30,40,50])

In [37]:
b=np.arange(4)

In [38]:
b

array([0, 1, 2, 3])

In [39]:
c=a-b

In [40]:
c

array([20, 29, 38, 47])

In [41]:
b**2

array([0, 1, 4, 9])

In [42]:
10*np.sin(a)

array([ 9.12945251, -9.88031624,  7.4511316 , -2.62374854])

In [43]:
a<35

array([ True,  True, False, False], dtype=bool)

Unlike in many matrix languages, the product operator * operates __elementwise__ in NumPy arrays. The matrix product can be performed using the __dot__ function or method:

In [44]:
A=np.array([1,1,0,1]).reshape(2,-1)

In [45]:
A

array([[1, 1],
       [0, 1]])

In [46]:
B=np.array([[2,0],[3,4]])

In [47]:
B

array([[2, 0],
       [3, 4]])

In [48]:
A*B

array([[2, 0],
       [0, 4]])

In [49]:
A.dot(B)

array([[5, 4],
       [3, 4]])

In [50]:
np.dot(A,B)

array([[5, 4],
       [3, 4]])

In [51]:
a=np.ones((2,3),dtype=int)

In [52]:
b=np.random.random((2,3))

In [53]:
b

array([[ 0.3447487 ,  0.12493976,  0.47344958],
       [ 0.15399852,  0.61127959,  0.34140507]])

In [54]:
a*=3

In [55]:
a

array([[3, 3, 3],
       [3, 3, 3]])

In [56]:
b+=a

In [57]:
b

array([[ 3.3447487 ,  3.12493976,  3.47344958],
       [ 3.15399852,  3.61127959,  3.34140507]])

In [61]:
a+=b  # b is not automatically converted to integer type

TypeError: Cannot cast ufunc add output from dtype('float64') to dtype('int64') with casting rule 'same_kind'

When operating with arrays of different types, the type of the resulting array corresponds to the more general or precise one (a behavior known as __upcasting__).

In [62]:
a=np.ones(3,dtype=np.int32)

In [63]:
b=np.linspace(0,np.pi,3)

In [64]:
b.dtype.name

'float64'

In [65]:
c=a+b

In [66]:
c

array([ 1.        ,  2.57079633,  4.14159265])

In [67]:
c.dtype.name

'float64'

In [68]:
d=np.exp(c*1j)

In [69]:
d

array([ 0.54030231+0.84147098j, -0.84147098+0.54030231j,
       -0.54030231-0.84147098j])

In [70]:
np.exp(pi*1j)

(-1+1.2246467991473532e-16j)

In [71]:
d.dtype.name

'complex128'

In [72]:
a=np.random.random((2,3))

In [73]:
a

array([[ 0.21755876,  0.76233191,  0.55473229],
       [ 0.88657767,  0.4386918 ,  0.59557438]])

In [74]:
a.sum()

3.4554668101324504

In [75]:
a.max()

0.88657767470076487

In [76]:
a.min()

0.21755876325059176

By default, these operations apply to the array **as though it were a list of numbers**, regardless of its shape. However, by specifying the axis parameter you can apply an operation **along the specified axis** of an array:

In [77]:
b=np.arange(12).reshape(3,4)

In [78]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [79]:
b.sum(axis=0)

array([12, 15, 18, 21])

In [80]:
b.min(axis=1)

array([0, 4, 8])

In [81]:
b.cumsum(axis=1)  # cumulative sum along each row

array([[ 0,  1,  3,  6],
       [ 4,  9, 15, 22],
       [ 8, 17, 27, 38]])

## Universal Functions

NumPy provides familiar mathematical functions such as sin, cos, and exp. In NumPy, these are called “universal functions”(ufunc). Within NumPy, these functions operate elementwise on an array, producing an array as output.

In [82]:
B=np.arange(3)
B

array([0, 1, 2])

In [83]:
np.exp(B)

array([ 1.        ,  2.71828183,  7.3890561 ])

In [84]:
np.sqrt(B)

array([ 0.        ,  1.        ,  1.41421356])

In [85]:
C=np.array([2.,-1.,4.])

In [86]:
np.add(B,C)

array([ 2.,  0.,  6.])

In [87]:
np.inner(B,C)

7.0

In [88]:
np.argmax(C)

2

In [89]:
np.argmin(C)

1

In [90]:
np.argsort(C)

array([1, 0, 2])

In [91]:
np.diff(C)

array([-3.,  5.])

In [92]:
np.sort(C)

array([-1.,  2.,  4.])

In [93]:
np.average(C)

1.6666666666666667

Usually such functions may have two versions. One is implemented in class.

In [94]:
C.sum()

5.0

In [95]:
C.sort()

In [96]:
C.argsort()

array([0, 1, 2])

## Indexing, Slicing and Iterating

In [97]:
a=np.arange(10)**3

In [98]:
a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

In [99]:
a[2]

8

In [100]:
a[2:5]

array([ 8, 27, 64])

In [101]:
a[:6:2]=-1000

In [148]:
a

array([-1000,     1, -1000,    27, -1000,   125,   216,   343,   512,   729])

In [149]:
a[::-1] #reversed a

array([  729,   512,   343,   216,   125, -1000,    27, -1000,     1, -1000])

In [150]:
a[5:3:-1]

array([  125, -1000])

In [151]:
a[3:5:-1]

array([], dtype=int64)

In [152]:
a[3::-1]

array([   27, -1000,     1, -1000])

In [153]:
for i in a:
    print(i**(1/3.))

nan
1.0
nan
3.0
nan
5.0
6.0
7.0
8.0
9.0


/usr/local/lib/python2.7/dist-packages/ipykernel/__main__.py:2: RuntimeWarning: invalid value encountered in power
  from ipykernel import kernelapp as app


In [155]:
def f(x,y):
    return 10*x+y

In [156]:
b=np.fromfunction(f,(5,4),dtype=int)

In [157]:
b

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

In [158]:
b[2,3]

23

In [159]:
b[0:5,1]

array([ 1, 11, 21, 31, 41])

In [160]:
b[:,1]

array([ 1, 11, 21, 31, 41])

In [161]:
b[1:3,:]

array([[10, 11, 12, 13],
       [20, 21, 22, 23]])

When fewer indices are provided than the number of axes, the missing indices are considered complete slices:

In [162]:
b[-1]                                  # the last row. Equivalent to b[-1,:]

array([40, 41, 42, 43])

The expression within brackets in b[i] is treated as an i followed by as many instances of : as needed to represent the remaining axes. NumPy also allows you to write this using dots as b[i,...].

The dots (...) represent as many colons as needed to produce a complete indexing tuple. For example, if x is a rank 5 array (i.e., it has 5 axes), then

   * x[1,2,...] is equivalent to x[1,2,:,:,:],

   * x[...,3] to x[:,:,:,:,3] and

   * x[4,...,5,:] to x[4,:,:,5,:].

In [111]:
def f(x,y,z):
    return 10**(x*2+y)+z

In [112]:
c=np.fromfunction(f,(2,2,3),dtype=int)

In [113]:
c

array([[[   1,    2,    3],
        [  10,   11,   12]],

       [[ 100,  101,  102],
        [1000, 1001, 1002]]])

In [114]:
c[1,...]

array([[ 100,  101,  102],
       [1000, 1001, 1002]])

In [115]:
c[1,...,2]

array([ 102, 1002])

**Iterating** over multidimensional arrays is done **with respect to the first axis**:

In [175]:
for row in b:
    print(row)

[0 1 2 3]
[10 11 12 13]
[20 21 22 23]
[30 31 32 33]
[40 41 42 43]


However, if one wants to perform an operation on each element in the array, one can use the **flat attribute** which is an **iterator** over all the elements of the array:

In [176]:
for element in b.flat:
    print(element)

0
1
2
3
10
11
12
13
20
21
22
23
30
31
32
33
40
41
42
43
