# Shape Manipulation

# Copies and Views

# Less Basic
## Boardcasting Rules

Broadcasting allows universal functions to deal in a meaningful way with inputs that **do not have exactly the same shape**.

The first rule of broadcasting is that if all input arrays do not have the same number of dimensions, a “1” will be repeatedly prepended to the shapes of the smaller arrays until all the arrays have the same number of dimensions.

In [1]:
import numpy as np
a=np.array([1,2,3])
b=np.array([1])

In [9]:
c=a+b #it is dangerous

In [10]:
c

array([2, 3, 4])

The second rule of broadcasting ensures that arrays with a size of 1 along a particular dimension act as if they had the size of the array with the largest shape along that dimension. The value of the array element is assumed to be the same along that dimension for the “broadcast” array.

In [18]:
a=np.array([[2,3,4]])
b=np.array([[1,2,4],[3,4,6]])
c=a+b
c

array([[ 3,  5,  8],
       [ 5,  7, 10]])

# Fancy Indexing and Index Tricks

NumPy offers more indexing facilities than regular Python sequences. In addition to **indexing by integers and slices**, as we saw before, arrays can be **indexed by arrays of integers and arrays of booleans**.

In [27]:
a=np.arange(12)**2
indices=np.array([1,1,2,3])
b=[1,2]
a[indices]

array([1, 1, 4, 9])

In [28]:
a[b] #please don't use list, tough it may be right sometimes

array([1, 4])

In [29]:
j = np.array( [ [ 3, 4], [ 9, 7 ] ] )  
a[j]

array([[ 9, 16],
       [81, 49]])

When the indexed array a is multidimensional, a single array of indices refers to the **first dimension** of a.

In [31]:
a=np.array([[1,2],[3,4],[5,6]])
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [37]:
k=np.array([[1,2,1],[0,1,0]])
a[k]

array([[[3, 4],
        [5, 6],
        [3, 4]],

       [[1, 2],
        [3, 4],
        [1, 2]]])

We can also give indexes for **more than one dimension**. The arrays of indices for each dimension must have the **same shape**.

In [44]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [45]:
i=np.array([[0,1],[2,1]])
j=np.array([[2,1],[0,1]])
a[i,j]

array([[2, 5],
       [8, 5]])

In [46]:
a[i,2]

array([[ 2,  6],
       [10,  6]])

In [47]:
a[:,j]

array([[[ 2,  1],
        [ 0,  1]],

       [[ 6,  5],
        [ 4,  5]],

       [[10,  9],
        [ 8,  9]]])

Naturally, we can put i and j in a sequence (say a list) and then do the indexing with the list. However, we can not do this by putting i and j into an array, because this array will be interpreted as indexing the first dimension of a.

In [48]:
l=[i,j]
a[l]

array([[2, 5],
       [8, 5]])

In [50]:
arr=np.array([i,j]) # to index the first dimension.

In [51]:
a[arr]

array([[[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7]],

        [[ 8,  9, 10, 11],
         [ 4,  5,  6,  7]]],


       [[[ 8,  9, 10, 11],
         [ 4,  5,  6,  7]],

        [[ 0,  1,  2,  3],
         [ 4,  5,  6,  7]]]])

In [52]:
a[tuple(arr)]

array([[2, 5],
       [8, 5]])

The most natural way one can think of for boolean indexing is to use boolean arrays that have the same shape as the original array:

In [53]:
a=np.arange(12).reshape(3,4)

In [54]:
b=a>4

In [55]:
b

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]], dtype=bool)

In [56]:
a[b] # 1d array with the selected elements

array([ 5,  6,  7,  8,  9, 10, 11])

This property can be very useful in assignments:

In [57]:
a[b]=0

In [58]:
a

array([[0, 1, 2, 3],
       [4, 0, 0, 0],
       [0, 0, 0, 0]])

The second way of indexing with booleans is more similar to integer indexing; for each dimension of the array we give a 1D boolean array selecting the slices we want. Note that the length of the 1D boolean array must coincide with the length of the dimension (or axis) you want to slice.

In [59]:
a = np.arange(12).reshape(3,4)
b1 = np.array([False,True,True]) 
b2 = np.array([True,False,True,False])

In [60]:
a[b1]

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [63]:
a[b1,:2]

array([[4, 5],
       [8, 9]])

In [64]:
a[:,b2]

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10]])

In [67]:
a[b1,b2] #don't do this.

array([ 4, 10])